version: '3.3'

volumes:
  static:
  media:
  db:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: pgorshkova/foodgram_backend:latest
    restart: always
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - static:/app/static/
      - media:/app/media/
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    image: pgorshkova/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - frontend
      - backend